version: "3.7"
services:
  user-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userexample
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Welc0me@123#$
    restart: always
    networks:
      - app-network
    ports:
      - 8080:8080
    depends_on:
      - mysql

  validation-app:
    build:
      context: D:/Downloads/gs-multi-module-main/Validation/
      dockerfile: Dockerfile
    container_name: validation-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userexample
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Welc0me@123#$
    restart: always
    networks:
      - app-network
    ports:
      - 8081:8081
    depends_on:
      - mysql

  mysql:
    image: "mysql:latest"
    container_name: mysql-app
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: userexample
      MYSQL_USER: sa
      MYSQL_PASSWORD: Welc0me@123#$
      MYSQL_ROOT_PASSWORD: Welc0me@123#$
    networks:
      - app-network
networks:
  app-network:
    driver: bridge